# -*- coding: utf-8 -*-
"""Atividade03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIKAzr_Fo81lzI86wKTcSU9TRBqS2vC5

# Nova seção
"""

import csv

# Dados a serem escritos
dados = [
    ["Nome", "Idade"],
    ["Ana", 25],
    ["Bruno", 30],
    ["Carla", 22],
    ["Daniel", 28],
    ["Eduardo", 35]
]

# Criando o arquivo CSV
with open("dados.csv", "w", newline="", encoding="utf-8") as arquivo:
    escritor = csv.writer(arquivo)
    escritor.writerows(dados)

# Ler o arquivo CSV e armazenar os dados em uma lista
dados_lista = []
with open("dados.csv", "r", newline="", encoding="utf-8") as arquivo:
    leitor = csv.reader(arquivo)
    next(leitor)  # Pular o cabeçalho
    for linha in leitor:
        nome, idade = linha
        dados_lista.append((nome, int(idade)))

# Solicitar nome ao usuário
nome_digitado = input("Digite um nome: ")

# Verificar se o nome está na lista
nomes = {nome: idade for nome, idade in dados_lista}
if nome_digitado in nomes:
    idade_digitada = nomes[nome_digitado]
    idade_maxima = max(nomes.values())
    if idade_digitada == idade_maxima:
        print(f"{nome_digitado} tem {idade_digitada} anos, é a pessoa mais velha da lista.")
    else:
        print(f"{nome_digitado} tem {idade_digitada} anos, não é a pessoa mais velha da lista.")
else:
    print("Nome não encontrado.")